name: OpenPGM
main: io.github.Aaron1011.openpgm.OpenPGM
version: 1.0.0

commands:
    loadworld:
        description: Load the specified world
        usage:  /loadworld <world>
        permission: OpenPGM.loadWorld
        permission-message: You don't have permission to use /loadworld
